export enum Config {
    NAME = 'name',
    PORT = 'port',
    VERSION = 'version',
    BASEPATH = 'basepath',
    DB_HOST = 'db.host',
    DB_PORT = 'db.port',
    DB_USER = 'db.username',
    DB_PASSWORD = 'db.password',
    DB_NAME = 'db.database',
    JWT_SECRET = 'access_secret',
    ACCESS_TOKEN_EXPIRY = 'access_expiresIn',
    ISO_DATE_FORMAT = 'isoDateFormat',
    APP_TIMEZONE = 'timezone',
    REDIS_TTL = 'redis.ttl',
    REDIS_HOST = 'redis.host',
    REDIS_PORT = 'redis.port',
    REDIS_PASSWORD = 'redis.password',
    FCM_KEY_PATH = 'fcm.keyPath'
}
